apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-configs
  namespace: kube-prom
data:
  alertmanager.yml: |-
    # 全局配置
    global:
      smtp_smarthost: 'smtp.qq.com:25'
      smtp_from: '572891887@qq.com'  	
      smtp_auth_username: '572891887@qq.com'
      smtp_auth_password: 'cacrhjqvhbirbebf'
      smtp_hello: 'qq.com'
      smtp_require_tls: false
    
    # 加载模板的路径
    templates:
      - '/etc/alertmanager/template/*.tmpl'
    
    # 路由规则
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 30s
      repeat_interval: 5m
      receiver: webhook-dingding-ops    # 默认发送给钉钉
    
      # 子路由
      routes:
      - match_re:
          job: 'kube.*'
        receiver: 'webhook-wechat-ops'	# 如果匹配到job=kube.*的都发送给微信
        continue: true
    
      - match_re:
          job: 'redis_exporter'
        receiver: 'email'		# 如果job=domain_exporter则都发送给email
        continue: true
    
    receivers:
    - name: 'email'
      email_configs:
      - to: 'oldxuedu@qq.com'
        send_resolved: true
        html: '{{ template "email.html" . }}'   # 发送邮件内容，调用该模板进行渲染

    - name: 'webhook-wechat-ops'
      webhook_configs:
      - url: 'http://webhook-wechat-svc:5001/alert?token=0e80968b-8d12-4339-85f1-27408df335a6'
      
    - name: 'webhook-dingding-ops'
      webhook_configs:
      - url: 'http://webhook-dingding-svc:5002/alert?token=cba69019eabece3ee3ca2f0b27dc2660b87f27239095e7676545de0373c845c3'
