apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: kube-prom
spec:
  selector:
    matchLabels:
      app: node-exporter

  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true

      # 添加污点容忍
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: "Exists"

      # 将宿主机目录声明为卷
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: /root

      # 容器的具体配置
      containers:
      - name: node
        image: prom/node-exporter:v1.7.0
        args:
        - "--web.listen-address=:9100"
        - "--web.max-requests=40"
        - "--collector.mountstats"
        - "--collector.systemd"
        - "--collector.ethtool"
        - "--collector.tcpstat"
        - "--path.procfs=/host/proc"
        - "--path.sysfs=/host/sys"
        - "--path.rootfs=/host/root"
        ports:
        - containerPort: 9100
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: proc
          mountPath: /host/proc
        - name: sys
          mountPath: /host/sys
        - name: root
          mountPath: /host/root
